language: node_js

node_js:
    - "4"
    - "6"
    - "node"

sudo: false

env:
    - HAPI_VERSION="13"
    - HAPI_VERSION="14"
    - HAPI_VERSION="15"

install:
    - npm install
    - npm install hapi@$HAPI_VERSION

